use("przepisy");

db.obiady.insertMany([
  {
    _id: 1,
    name: "Schabowy z ziemniakami i mizerią",
    ingredients: [
      { name: "kotlety schabowe", quantity: 2, unit: "sztuki" },
      { name: "ziemniaki", quantity: 4, unit: "sztuki" },
      { name: "ogórek zielony", quantity: 1, unit: "sztuka" },
      { name: "śmietana", quantity: 3, unit: "łyżki" },
      { name: "sól" },
      { name: "pieprz" },
    ],
    instructions:
      "Ziemniaki obierz, ugotuj w osolonej wodzie (ok. 20 minut).Kotlety schabowe rozbij tłuczkiem, posól i popieprz. Obtocz w mące, następnie w rozkłóconym jajku i bułce tartej. Smaż kotlety na rozgrzanym oleju po 3–4 minuty z każdej strony, aż będą złociste. Ogórek pokrój w plasterki, posól i wymieszaj ze śmietaną. Dopraw pieprzem do smaku. Podawaj kotlety z ziemniakami i mizerią.",
    meal_type: "obiady",
    prep_time: 40,
    calories: 720,
    isVege: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 2,
    name: "Pierogi z mięsem",
    ingredients: [
      { name: "mąka pszenna", quantity: 2, unit: "szklanki" },
      { name: "jajko", quantity: 1, unit: "sztuka" },
      { name: "woda", quantity: 0.5, unit: "szklanki" },
      { name: "sól" },
      { name: "ugotowane mięso", quantity: 300, unit: "g" },
      { name: "cebula", quantity: 1, unit: "sztuka" },
      { name: "masło", quantity: 1, unit: "łyżka" },
    ],
    instructions:
      "Zagnieć ciasto z mąki, jajka, wody i soli. Odstaw na 15 minut. Mięso zmiel, cebulę zeszklij na maśle i dodaj do mięsa. Dopraw solą i pieprzem. Ciasto rozwałkuj cienko, wykrawaj kółka. Nakładaj farsz i zlepiaj pierogi. Gotuj pierogi w osolonej wodzie przez 5 minut od momentu wypłynięcia. Podawaj z podsmażoną cebulką.",
    meal_type: "obiady",
    prep_time: 50,
    calories: 560,
    isVege: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 3,
    name: "Makaron z pesto z awokado",
    ingredients: [
      { name: "makaron spaghetti", quantity: 200, unit: "g" },
      { name: "awokado", quantity: 1, unit: "sztuka" },
      { name: "czosnek", quantity: 1, unit: "ząbek" },
      { name: "świeża bazylia", quantity: 1, unit: "garść" },
      { name: "oliwa z oliwek", quantity: 2, unit: "łyżki" },
      { name: "sok z cytryny", quantity: 1, unit: "łyżka" },
      { name: "sól" },
      { name: "pieprz" },
    ],
    instructions:
      "Ugotuj makaron al dente w osolonej wodzie zgodnie z instrukcją na opakowaniu (ok. 8–10 minut). W międzyczasie przekrój awokado na pół, usuń pestkę i wydrąż miąższ. Do blendera wrzuć awokado, obrany ząbek czosnku, bazylię, oliwę z oliwek oraz sok z cytryny. Zmiksuj na gładkie pesto. Dopraw solą i pieprzem do smaku. Gotowe pesto wymieszaj z odcedzonym makaronem. Można udekorować listkami bazylii i skropić dodatkową oliwą.",
    meal_type: "obiady",
    prep_time: 20,
    calories: 540,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 4,
    name: "Curry warzywne z batatami",
    ingredients: [
      { name: "batat", quantity: 1, unit: "sztuka" },
      { name: "mleko kokosowe", quantity: 400, unit: "ml" },
      { name: "marchewka", quantity: 1, unit: "sztuka" },
      { name: "szpinak", quantity: 1, unit: "garść" },
      { name: "cebula", quantity: 1, unit: "sztuka" },
      { name: "czosnek", quantity: 2, unit: "ząbki" },
      { name: "pasta curry", quantity: 2, unit: "łyżeczki" },
      { name: "olej kokosowy", quantity: 1, unit: "łyżeczka" },
    ],
    instructions:
      "Przygotowanie: Batata i marchewkę obierz, pokrój w kostkę. Cebulę i czosnek drobno posiekaj. W garnku rozgrzej olej kokosowy, zeszklij cebulę i czosnek. Dodaj pastę curry i mieszaj przez 1 minutę. Dorzuć bataty i marchewkę, podsmażaj przez 3–4 minuty. Wlej mleko kokosowe i gotuj na średnim ogniu przez ok. 15 minut, aż warzywa będą miękkie. Dodaj szpinak, mieszając, aby zmiękł (2–3 minuty). Dopraw solą i pieprzem.Podawaj z ryżem basmati lub kaszą.",
    meal_type: "obiady",
    prep_time: 30,
    calories: 610,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 5,
    name: "Zupa pomidorowa z ryżem",
    ingredients: [
      { name: "bulion drobiowy", quantity: 1, unit: "l" },
      { name: "pomidory krojone z puszki", quantity: 400, unit: "g" },
      { name: "ryż", quantity: 100, unit: "g" },
      { name: "koncentrat pomidorowy", quantity: 2, unit: "łyżki" },
      { name: "cebula", quantity: 1, unit: "sztuka" },
      { name: "masło", quantity: 1, unit: "łyżka" },
      { name: "sól" },
      { name: "pieprz" },
      { name: "bazylia" },
    ],
    instructions:
      "W garnku rozgrzej masło i zeszklij pokrojoną cebulę. Dodaj pomidory z puszki i smaż przez 5 minut. Wlej bulion, dodaj koncentrat pomidorowy i zagotuj. Wsyp ryż i gotuj przez 15 minut, aż będzie miękki. Dopraw solą, pieprzem i bazylią do smaku. Podawaj na ciepło.",
    meal_type: "obiady",
    prep_time: 30,
    calories: 390,
    isVege: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 6,
    name: "Kotlety mielone z ziemniakami i buraczkami",
    ingredients: [
      { name: "mięso mielone wieprzowo-wołowe", quantity: 300, unit: "g" },
      { name: "jajko", quantity: 1, unit: "sztuka" },
      { name: "bułka tarta", quantity: 2, unit: "łyżki" },
      { name: "cebula", quantity: 1, unit: "sztuka" },
      { name: "ziemniaki", quantity: 5, unit: "sztuk" },
      { name: "burak", quantity: 1, unit: "sztuka" },
      { name: "olej" },
      { name: "cukier", quantity: 1, unit: "łyżeczka" },
      { name: "sól" },
      { name: "pieprz" },
    ],
    instructions:
      "Mięso wymieszaj z jajkiem, bułką tartą, posiekaną cebulą oraz przyprawami. Uformuj kotlety. Smaż na rozgrzanym oleju po 4–5 minut z każdej strony. Ziemniaki obierz, ugotuj w osolonej wodzie. Buraka ugotuj lub upiecz, zetrzyj na tarce, dopraw cukrem, solą i odrobiną octu. Podawaj kotlety z ziemniakami i buraczkami.",
    meal_type: "obiady",
    prep_time: 50,
    calories: 640,
    isVege: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 7,
    name: "Gołąbki z sosem pomidorowym",
    ingredients: [
      { name: "główka kapusty", quantity: 1, unit: "sztuka" },
      { name: "mięso mielone", quantity: 300, unit: "g" },
      { name: "ryż", quantity: 100, unit: "g" },
      { name: "cebula", quantity: 1, unit: "sztuka" },
      { name: "pomidory z puszki", quantity: 400, unit: "g" },
      { name: "majeranek", quantity: 1, unit: "łyżeczka" },
      { name: "sól" },
      { name: "pieprz" },
    ],
    instructions:
      "Z kapusty usuń twardy głąb, sparz liście wrzątkiem. Ryż ugotuj na półtwardo, wymieszaj z mięsem, podsmażoną cebulą, solą i pieprzem. Farsz zawijaj w liście kapusty, formując gołąbki. Ułóż je w garnku. Zalej pomidorami zmiksowanymi z wodą, dodaj majeranek i gotuj pod przykryciem ok. 40 minut.",
    meal_type: "obiady",
    prep_time: 60,
    calories: 580,
    isVege: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 8,
    name: "Rosół z makaronem",
    ingredients: [
      { name: "udka z kurczaka", quantity: 2, unit: "sztuki" },
      { name: "marchewka", quantity: 2, unit: "sztuki" },
      { name: "pietruszka", quantity: 1, unit: "sztuka" },
      { name: "seler", quantity: 1, unit: "kawałek" },
      { name: "cebula", quantity: 1, unit: "sztuka" },
      { name: "makaron nitki", quantity: 100, unit: "g" },
      { name: "natka pietruszki" },
      { name: "sól" },
      { name: "pieprz" },
    ],
    instructions:
      "Mięso umyj, włóż do garnka z warzywami, cebulą i solą. Gotuj na małym ogniu ok. 1,5 godziny. Odcedź rosół, ugotuj makaron w osolonej wodzie. Podawaj z natką pietruszki i makaronem.",
    meal_type: "obiady",
    prep_time: 90,
    calories: 450,
    isVege: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 9,
    name: "Fasolka po bretońsku (wersja wege)",
    ingredients: [
      { name: "ugotowana biała fasola", quantity: 400, unit: "g" },
      { name: "cebula", quantity: 1, unit: "sztuka" },
      { name: "czosnek", quantity: 2, unit: "ząbki" },
      { name: "pomidory krojone z puszki", quantity: 400, unit: "g" },
      { name: "majeranek", quantity: 1, unit: "łyżeczka" },
      { name: "słodka papryka", quantity: 1, unit: "łyżeczka" },
      { name: "olej", quantity: 1, unit: "łyżka" },
      { name: "sól" },
      { name: "pieprz" },
    ],
    instructions:
      "Cebulę i czosnek drobno posiekaj. Na patelni rozgrzej olej i zeszklij cebulę z czosnkiem. Dodaj pomidory z puszki, majeranek i słodką paprykę. Gotuj na średnim ogniu przez 10 minut. Dorzuć ugotowaną fasolę i gotuj całość przez kolejne 10 minut, aż smaki się połączą. Dopraw solą i pieprzem według uznania. Jeśli sos jest zbyt gęsty, możesz dodać odrobinę wody. Podawaj na ciepło z pieczywem lub kaszą.",
    meal_type: "obiady",
    prep_time: 30,
    calories: 450,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 10,
    name: "Karkówka pieczona z ziemniakami",
    ingredients: [
      { name: "karkówka wieprzowa", quantity: 400, unit: "g" },
      { name: "ziemniaki", quantity: 4, unit: "sztuki" },
      { name: "czosnek", quantity: 2, unit: "ząbki" },
      { name: "olej", quantity: 2, unit: "łyżki" },
      { name: "sól" },
      { name: "pieprz" },
      { name: "majeranek" },
    ],
    instructions:
      "Karkówkę natrzyj olejem, przeciśniętym czosnkiem, solą, pieprzem i majerankiem. Ziemniaki obierz, pokrój na ćwiartki. Mięso i ziemniaki ułóż w naczyniu żaroodpornym, piecz przez 60 minut w 180°C. Podawaj gorące z surówką.",
    meal_type: "obiady",
    prep_time: 70,
    calories: 700,
    isVege: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 11,
    name: "Placki ziemniaczane ze śmietaną",
    ingredients: [
      { name: "ziemniaki", quantity: 4, unit: "sztuki" },
      { name: "jajko", quantity: 1, unit: "sztuka" },
      { name: "mąka pszenna", quantity: 2, unit: "łyżki" },
      { name: "sól" },
      { name: "pieprz" },
      { name: "olej" },
      { name: "śmietana", quantity: 3, unit: "łyżki" },
    ],
    instructions:
      "Ziemniaki obierz i zetrzyj na tarce. Dodaj jajko, mąkę, sól i pieprz. Wymieszaj. Na rozgrzanej patelni smaż placki na złoty kolor. Podawaj ze śmietaną.",
    meal_type: "obiady",
    prep_time: 25,
    calories: 420,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 12,
    name: "Spaghetti bolognese",
    ingredients: [
      { name: "makaron spaghetti", quantity: 200, unit: "g" },
      { name: "mięso mielone", quantity: 300, unit: "g" },
      { name: "pomidory krojone z puszki", quantity: 400, unit: "g" },
      { name: "cebula", quantity: 1, unit: "sztuka" },
      { name: "czosnek", quantity: 1, unit: "ząbek" },
      { name: "sól" },
      { name: "pieprz" },
      { name: "oregano" },
    ],
    instructions:
      "Cebulę i czosnek posiekaj, zeszklij na oliwie. Dodaj mięso i smaż przez 5 minut. Wlej pomidory, dodaj oregano, sól i pieprz. Duś przez 20 minut. Makaron ugotuj i wymieszaj z sosem.",
    meal_type: "obiady",
    prep_time: 35,
    calories: 590,
    isVege: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 13,
    name: "Naleśniki z mięsem i pieczarkami",
    ingredients: [
      { name: "mąka pszenna", quantity: 1, unit: "szklanka" },
      { name: "jajko", quantity: 1, unit: "sztuka" },
      { name: "mleko", quantity: 1, unit: "szklanka" },
      { name: "mięso mielone", quantity: 200, unit: "g" },
      { name: "pieczarki", quantity: 100, unit: "g" },
      { name: "cebula", quantity: 1, unit: "sztuka" },
      { name: "olej" },
      { name: "sól" },
      { name: "pieprz" },
    ],
    instructions:
      "Z ciasta usmaż naleśniki. Mięso podsmaż z cebulą i pieczarkami. Dopraw solą i pieprzem. Naleśniki nadziewaj farszem i podpiecz na patelni.",
    meal_type: "obiady",
    prep_time: 45,
    calories: 540,
    isVege: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 14,
    name: "Kotlety z ciecierzycy z kaszą jaglaną",
    ingredients: [
      { name: "ugotowana ciecierzyca", quantity: 400, unit: "g" },
      { name: "kasza jaglana", quantity: 1, unit: "szklanka" },
      { name: "cebula", quantity: 1, unit: "sztuka" },
      { name: "czosnek", quantity: 2, unit: "ząbki" },
      { name: "bułka tarta", quantity: 2, unit: "łyżki" },
      { name: "sól" },
      { name: "pieprz" },
      { name: "kumin" },
      { name: "olej" },
    ],
    instructions:
      "Cebulę i czosnek drobno posiekaj, podsmaż na odrobinie oleju aż zmiękną. Ciecierzycę zmiksuj w blenderze na gładką masę. Dodaj ugotowaną kaszę jaglaną, podsmażoną cebulę z czosnkiem, bułkę tartą oraz przyprawy. Dokładnie wymieszaj. Formuj kotlety, lekko spłaszczając, aby były równomiernie usmażone. Rozgrzej patelnię z olejem i smaż kotlety z obu stron po 3–4 minuty do złocistego koloru. Podawaj z sałatką lub sosem pomidorowym.",
    meal_type: "obiady",
    prep_time: 35,
    calories: 380,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 15,
    name: "Tofu w sosie teriyaki z ryżem",
    ingredients: [
      { name: "tofu", quantity: 200, unit: "g" },
      { name: "ryż", quantity: 100, unit: "g" },
      { name: "syrop kolonowy", quantity: 1, unit: "łyżka" },
      { name: "olej sezamowy", quantity: 1, unit: "łyżka" },
      { name: "starty imbir", quantity: 1, unit: "łyżka" },
      { name: "sezem do posypania" },
    ],
    instructions:
      "Tofu pokrój w kostkę i osusz ręcznikiem papierowym. Przygotuj marynatę: wymieszaj sos sojowy, syrop klonowy, olej sezamowy i starty imbir. Dodaj tofu, delikatnie mieszając, i odstaw na 15 minut.W tym czasie ugotuj ryż według instrukcji na opakowaniu.Na rozgrzanej patelni smaż tofu na złocisty kolor (ok. 5 minut), następnie wlej resztę marynaty i smaż przez kolejne 2 minuty.Podawaj z ugotowanym ryżem, posyp sezamem.",
    meal_type: "obiady",
    prep_time: 35,
    calories: 520,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 16,
    name: "Pieczone warzywa z hummusem",
    ingredients: [
      { name: "marchewka", quantity: 1, unit: "szt." },
      { name: "batat", quantity: 1, unit: "szt." },
      { name: "cukinia", quantity: 1, unit: "szt." },
      { name: "oliwa z oliwek", quantity: 2, unit: "łyżki" },
      { name: "sól", quantity: 1, unit: "szczypta" },
      { name: "pieprz", quantity: 1, unit: "szczypta" },
      { name: "zioła prowansalskie", quantity: 1, unit: "szczypta" },
      { name: "hummus", quantity: 100, unit: "g" },
    ],
    instructions:
      "Warzywa obierz i pokrój na kawałki (słupki lub kostkę). Ułóż na blaszce wyłożonej papierem do pieczenia. Skrop oliwą, posyp przyprawami i dokładnie wymieszaj. Piecz w piekarniku nagrzanym do 200°C przez ok. 25–30 minut, aż warzywa będą miękkie i lekko przypieczone. Podawaj z hummusem jako dipem.",
    meal_type: "obiady",
    prep_time: 40,
    calories: 480,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 17,
    name: "Risotto grzybowe",
    ingredients: [
      { name: "ryż arborio", quantity: 1, unit: "szklanka" },
      { name: "pieczarki lub leśne grzyby", quantity: 200, unit: "g" },
      { name: "cebula", quantity: 1, unit: "szt." },
      { name: "czosnek", quantity: 2, unit: "ząbki" },
      { name: "bulion warzywny", quantity: 500, unit: "ml" },
      { name: "oliwa z oliwek", quantity: 1, unit: "łyżka" },
      { name: "masło roślinne", quantity: 1, unit: "łyżeczka" },
      { name: "sól", quantity: 1, unit: "szczypta" },
      { name: "pieprz", quantity: 1, unit: "szczypta" },
    ],
    instructions:
      "Cebulę i czosnek drobno posiekaj, pieczarki pokrój w plastry. W dużym garnku rozgrzej oliwę z oliwek i podsmaż cebulę z czosnkiem na złocisty kolor. Dodaj pieczarki i smaż przez ok. 5 minut, aż się zrumienią. Wsyp ryż do garnka i mieszaj przez 2 minuty, aż stanie się szklisty. Stopniowo dolewaj bulion warzywny (po jednej chochli), za każdym razem mieszając ryż i czekając, aż płyn zostanie wchłonięty. Powtarzaj proces przez około 20 minut. Gdy ryż będzie miękki i kremowy, dodaj masło roślinne oraz sól i pieprz do smaku. Podawaj gorące risotto posypane świeżą natką pietruszki lub szczypiorkiem.",
    meal_type: "obiady",
    prep_time: 40,
    calories: 470,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 18,
    name: "Gulasz z soczewicy",
    ingredients: [
      { name: "czerwona soczewica", quantity: 1, unit: "szklanka" },
      { name: "marchewka", quantity: 1, unit: "szt." },
      { name: "pietruszka", quantity: 1, unit: "szt." },
      { name: "cebula", quantity: 1, unit: "szt." },
      { name: "puszka krojonych pomidorów", quantity: 1, unit: "400 g" },
      { name: "czosnek", quantity: 2, unit: "ząbki" },
      { name: "olej", quantity: 1, unit: "łyżka" },
      { name: "kumin", quantity: 1, unit: "łyżeczka" },
      { name: "sól", quantity: 1, unit: "szczypta" },
      { name: "pieprz", quantity: 1, unit: "szczypta" },
    ],
    instructions:
      "Cebulę i czosnek drobno posiekaj. Marchewkę i pietruszkę obierz i pokrój w kostkę. W dużym garnku rozgrzej olej i zeszklij cebulę z czosnkiem. Dodaj pokrojone warzywa i smaż przez 3–4 minuty. Wsyp suchą soczewicę, wlej pomidory z puszki i dodaj szklankę wody. Dopraw kuminem, solą i pieprzem. Gotuj na średnim ogniu przez 20–25 minut, mieszając od czasu do czasu, aż soczewica będzie miękka, a gulasz gęsty. Podawaj z chlebem, ryżem lub kaszą.",
    meal_type: "obiady",
    prep_time: 35,
    calories: 420,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 19,
    name: "Placki z cukinii i marchewki",
    ingredients: [
      { name: "cukinia", quantity: 1, unit: "średnia" },
      { name: "marchewki", quantity: 2, unit: "szt." },
      { name: "mąka pszenna lub owsiana", quantity: 3, unit: "łyżki" },
      { name: "sól", quantity: 1, unit: "łyżeczka" },
      { name: "pieprz", quantity: 1, unit: "szczypta" },
      { name: "olej do smażenia", quantity: 1, unit: "łyżka" },
    ],
    instructions:
      "Cukinię i marchewki umyj, obierz i zetrzyj na tarce o grubych oczkach. Warzywa odciśnij z nadmiaru wody, przełóż do miski i dodaj mąkę, sól oraz pieprz. Dokładnie wymieszaj. Rozgrzej patelnię z odrobiną oleju. Nakładaj łyżką porcje masy warzywnej, formując placki. Smaż placki z obu stron na złocisty kolor (po ok. 3 minuty z każdej strony). Podawaj z sosem jogurtowo-czosnkowym lub ketchupem.",
    meal_type: "obiady",
    prep_time: 25,
    calories: 320,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 20,
    name: "Gulasz z bakłażana i pomidorów",
    ingredients: [
      { name: "bakłażan", quantity: 1, unit: "duży" },
      { name: "cebula", quantity: 1, unit: "szt." },
      { name: "puszka krojonych pomidorów", quantity: 1, unit: "400 g" },
      { name: "czosnek", quantity: 2, unit: "ząbki" },
      { name: "oregano", quantity: 1, unit: "łyżeczka" },
      { name: "oliwa z oliwek", quantity: 1, unit: "łyżka" },
      { name: "sól", quantity: 1, unit: "szczypta" },
      { name: "pieprz", quantity: 1, unit: "szczypta" },
    ],
    instructions:
      "Bakłażana umyj i pokrój w kostkę. Cebulę i czosnek drobno posiekaj. W garnku rozgrzej oliwę i podsmaż cebulę z czosnkiem przez 3–4 minuty. Dodaj pokrojonego bakłażana i smaż, mieszając, przez 5 minut.Wlej pomidory z puszki i dodaj oregano. Całość gotuj na średnim ogniu przez 15–20 minut, aż bakłażan będzie miękki.Dopraw solą i pieprzem do smaku. Podawaj z ryżem lub kaszą kuskus.",
    meal_type: "obiady",
    prep_time: 25,
    calories: 320,
    isVege: true,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]);
